### ISSUE TITLE
Arlanet.CopernicaNET.Sample project not working

### ISSUE THREAD

**Issue by jbreuer** [Arlanet/CopernicaNET#9]
When I try to use the Arlanet.CopernicaNET.Sample project it doesn't work. This is because I don't have the database created in Copernica yet. Do I first need to create the database in Copernica and update the Id in the [Client](https://github.com/Arlanet/CopernicaNET/blob/940f645f743b7fd91cf6f067f2f3ee23de129cc8/Src/CopernicaNET.Sample/Models/Client.cs) and [Product](https://github.com/Arlanet/CopernicaNET/blob/940f645f743b7fd91cf6f067f2f3ee23de129cc8/Src/CopernicaNET.Sample/Models/Product.cs) class?

I prefer to create the database with the API as well and use that Id on the classes. Is that possible?

We want to use CopernicaNET to transfer some data from Umbraco (not just members) to Copernica. This API looks really nice :-).

**Comment by ynzenu** [comment]
The CopernicaAccessToken has to be configured in the web.config. Automatically creating a copernica database from a class is not supported at the moment so you can add it yourself or create the database manually. An auto generated copernica database does sound interesting and I might be able to help you out depending on your deadline and my spare time.

This is really just a sample, not an example. You can review the code on how to implement your copernica implementation. Hope this helps.

**Comment by jbreuer** [comment]
Thanks for your response. I already configured the CopernicaAccessToken. I saw that Arlanet also created an [Umbraco package for Copernica](https://www.copernica.com/en/support/integrations/umbraco) that does support creating databases. Not sure if that source code is also available somewhere. 

We'll probably start development next week and we need to finish it a few weeks after that. I think it would be nice if the database and collection can be created based on Client and Product class. We're going to have a lot more classes for our implementation. Not sure if we only need to update the Sample project for this or also the CopernicaNET project because the CopernicaDatabase and CopernicaCollection attribute probably need different ways to set the Id.

**Comment by ynzenu** [comment]
Does the Umbraco package not have everything you need? It uses the 'old' SOAP api so the code is not viable for reusing with the REST api.

**Comment by jbreuer** [comment]
We also need to export a lot of data out of custom tables. The Umbraco package only does members I think.

**Comment by jbreuer** [comment]
After we created the database we might also have to update it if we have extra fields we want to store. Doing this with the API might be too much work. For now I'll try to create the database manually and than use the ids in the sample project. For now the ids are hard coded in the CopernicaDatabase and CopernicaCollection attribute. Can we change that or do we need to update the CopernicaNET source for that?

**Comment by ynzenu** [comment]
The database ids are configurable, you can find more info about it in this pull request: https://github.com/Arlanet/CopernicaNET/pull/1

**Comment by LennardF1989** [comment]
Hello Jeroen, currently the Attributes you mention both have hardcoded id's when you use them:
- Src/CopernicaNET/Attributes/CopernicaCollection.cs
- Src/CopernicaNET/Attributes/CopernicaDatabase.cs

But to answer your question: Yes, you can change this to your hearts wish, that's what it's for :)

However, I can understand this might not make it easy to configure Copernica for multiple environments sharing the same code-base. But you are in luck! There are two ways to go about this:
- Use a `CopernicaConfigurableProfile` or `CopernicaConfigurableSubProfile` to make your models. Also see PR #1 
- Override the two mentioned attributes with an own implementation to get the ID's from wherever you wish. The core of Copernica simply does a `GetCustomAttribute` on both of these attributes when it needs the Id. So, you could just make an extension of above two attributes, and overrule the constructor to pass in an Id you retrieve from say the `ConfigurationManager` or even fire a query to your database to get the proper Id's.

**Comment by jbreuer** [comment]
Thanks for options. I will do some experiments tomorrow to see how it goes.

**Comment by LennardF1989** [comment]
I'd advice against using the Configureable's. I just looked at that code and they should actually work like option two I gave you. Right now they are a complete copy of the CopernicaProfile/CopernicaSubProfile, whereas all it really needed was two overridden attributes to work...

**Comment by jbreuer** [comment]
Good tip :-). Option two it is.

**Comment by LennardF1989** [comment]
I just pushed a new version of the code fixing this "inconsistency". Also poses as an example on how to go about your own attributes that have to pull their Id's from wherever.

**Comment by LennardF1989** [comment]
And I updated the NuGet Package alongside with the Wiki to give you an example of usage: https://github.com/Arlanet/CopernicaNET/wiki

Spares you the time of having to dig through the Sample project ;)

**Comment by jbreuer** [comment]
Thank for the updated NuGet package and Wiki. It was a great help! I found some bugs and fixed those in this PR: https://github.com/Arlanet/CopernicaNET/pull/10

**Comment by jbreuer** [comment]
Thanks for merging the PR. Could you please also update the NuGet package?

**Comment by LennardF1989** [comment]
That's weird, I tested the `GetType()` for the attributes and it returned the right one. What kind of case did you ran into that you had to pass in the `typeof(Product)` specifically?

Otherwise `GetCustomAttributes` wouldn't even work to begin with...

EDIT: Oh, I see what I did there. I mixed two ideas I had...

**Comment by jbreuer** [comment]
When I used GetType() it returned the type of the attribute. Not the target class.

**Comment by LennardF1989** [comment]
Yea, I see where I went wrong with that. Updated the NuGet package to 1.0.7 :)
